### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [chadmmiles/project4#1]
This looks mostly really good, though I do a JavaScript error in the console:

> Uncaught Error: Bootstrap's JavaScript requires jQuery

Can you try to fix that then let me know when it's done? If you're not sure what to do and have questions, just let me know!
### Getting rid of `.DS_Store` clutter

OS X automatically generates hidden `.DS_Store` files and by default, Git will include them your commits. To get rid of this clutter in our Git repos, you can [check out this link](http://stackoverflow.com/questions/107701/how-can-i-remove-ds-store-files-from-a-git-repository).
### Ruby indentation

The standard indentation for Ruby (`.rb`) files is actually with two-space soft-tabs rather than hard-tabs. See if you can update your text editor to use two-space soft-tabs for all Ruby files. If you have trouble figuring it out, just let me know and I'll be happy to point you in the right direction.

**Comment by chadmmiles** [comment]
I added Jquery references to all of my pages above the bootstrap.js reference but this hasn't taken care of the issue. Is there something else I need to do or do differently?

**Comment by chrisvfritz** [comment]
It looks like it's taken care of the issue for me. I don't see that error in the JavaScript console anymore on Heroku. I'm giving this a :+1:. What indicated to you that the problem wasn't solved?

**Comment by chadmmiles** [comment]
When I first checked it didn't seem to be solved, but then as I was working on today's assignments I was able to figure it out and make the proper change.

**Comment by chrisvfritz** [comment]
Excellent! :smiley:
